/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author anzt0
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    public SiswaView siswaView;
    public MapelView mapelView;
    public PengajarView pengajarView;
    public PendaftaranView pendaftaranview;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemSiswa = new javax.swing.JMenuItem();
        itemPengajar = new javax.swing.JMenuItem();
        itemMapel = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemPendaftaran = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout menuDesktopLayout = new javax.swing.GroupLayout(menuDesktop);
        menuDesktop.setLayout(menuDesktopLayout);
        menuDesktopLayout.setHorizontalGroup(
            menuDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        menuDesktopLayout.setVerticalGroup(
            menuDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        getContentPane().add(menuDesktop, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Kelola Bimbel");

        itemSiswa.setText("Siswa");
        itemSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSiswaActionPerformed(evt);
            }
        });
        jMenu1.add(itemSiswa);

        itemPengajar.setText("Pengajar");
        itemPengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPengajarActionPerformed(evt);
            }
        });
        jMenu1.add(itemPengajar);

        itemMapel.setText("Mata Pelajaran");
        itemMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMapelActionPerformed(evt);
            }
        });
        jMenu1.add(itemMapel);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pendaftaran");

        itemPendaftaran.setText("Kelola");
        itemPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPendaftaranActionPerformed(evt);
            }
        });
        jMenu2.add(itemPendaftaran);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSiswaActionPerformed
        // TODO add your handling code here:
        if (mapelView == null) {
            siswaView = new SiswaView();
            menuDesktop.add(siswaView);
        } else {
            siswaView.toFront();
        }
        siswaView.setVisible(true);
    }//GEN-LAST:event_itemSiswaActionPerformed

    private void itemPengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPengajarActionPerformed
        // TODO add your handling code here:
        if (pengajarView == null) {
            pengajarView = new PengajarView();
            menuDesktop.add(pengajarView);
        } else {
            pengajarView.toFront();
        }
        pengajarView.setVisible(true);
    }//GEN-LAST:event_itemPengajarActionPerformed

    private void itemMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMapelActionPerformed
         // TODO add your handling code here:
         
        if (mapelView == null) {
            mapelView = new MapelView();
            menuDesktop.add(mapelView);
        } else {
            mapelView.toFront();
        }
        mapelView.setVisible(true);
    }//GEN-LAST:event_itemMapelActionPerformed

    private void itemPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPendaftaranActionPerformed
        // TODO add your handling code here:
          if (pendaftaranview == null) {
            pendaftaranview = new PendaftaranView();
            menuDesktop.add(pendaftaranview);
        } else {
            pendaftaranview.toFront();
        }
        pendaftaranview.setVisible(true);
    }//GEN-LAST:event_itemPendaftaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMapel;
    private javax.swing.JMenuItem itemPendaftaran;
    private javax.swing.JMenuItem itemPengajar;
    private javax.swing.JMenuItem itemSiswa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane menuDesktop;
    // End of variables declaration//GEN-END:variables
}
