/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PendaftaranController;
import controller.ProdukController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import main.App;
import model.Mapel;
import model.Pendaftaran;
import model.Pengajar;
import model.Produk;
import model.Siswa;


/**
 *
 * @author anzt0
 */
public class PendaftaranView extends javax.swing.JInternalFrame {

    private final Pendaftaran pendaftaran;
    private Mapel mapel;
    private Pengajar pengajar;
    private Siswa siswa;
    private List<Pendaftaran> listPendaftaran;
    private PendaftaranController pendaftaranController;
    
    /**
     * Creates new form ProdukView
     */
    public PendaftaranView() {
        initComponents();
        pendaftaran = new Pendaftaran();
        siswa = new Siswa();
        mapel = new Mapel();
        pengajar = new Pengajar();
        pendaftaranController = new PendaftaranController(this);
        pendaftaranController.loadSatuan();
        refreshTable();
        
    }

    public JComboBox<String> getComboMapel() {
        return comboMapel;
    }

    public JComboBox<String> getComboPengajar() {
        return comboPengajar;
    }

    public JComboBox<String> getComboSiswa() {
        return comboSiswa;
    }

    public JRadioButton getjRadioBelumLunas() {
        return jRadioBelumLunas;
    }

    public JRadioButton getjRadioLunas() {
        return jRadioLunas;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTable getTabelPendaftaran() {
        return tabelPendaftaran;
    }

    public JButton getTombolBaru() {
        return tombolBaru;
    }

    public JButton getTombolHapus() {
        return tombolHapus;
    }

    public JButton getTombolSimpan() {
        return tombolSimpan;
    }

    public JButton getTombolUbah() {
        return tombolUbah;
    }
    


    
    private void refreshTable(){
        listPendaftaran = App.masterService.getAllPendaftaran();
        tabelPendaftaran.setModel(new ProdukTableModel(listPendaftaran));
    }

    private void initListener(){
        tabelPendaftaran.getSelectionModel().addListSelectionListener((ListSelectionEvent lse) -> {
            pendaftaranController.loadData(pendaftaran, listPendaftaran);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboMapel = new javax.swing.JComboBox<>();
        comboSiswa = new javax.swing.JComboBox<>();
        comboPengajar = new javax.swing.JComboBox<>();
        jRadioBelumLunas = new javax.swing.JRadioButton();
        jRadioLunas = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        tombolHapus = new javax.swing.JButton();
        tombolUbah = new javax.swing.JButton();
        tombolSimpan = new javax.swing.JButton();
        tombolBaru = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPendaftaran = new javax.swing.JTable();

        setClosable(true);
        setTitle("Form Input Produk");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel2.setText("Nama");

        jLabel3.setText("Mapel");

        jLabel4.setText("Pengajar");

        jRadioBelumLunas.setText("Belum Lunas");
        jRadioBelumLunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBelumLunasActionPerformed(evt);
            }
        });

        jRadioLunas.setText("Lunas");
        jRadioLunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioLunasActionPerformed(evt);
            }
        });

        jLabel7.setText("Status");

        tombolHapus.setText("Hapus");

        tombolUbah.setText("Ubah");

        tombolSimpan.setText("Simpan");
        tombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSimpanActionPerformed(evt);
            }
        });

        tombolBaru.setText("Baru");
        tombolBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolBaruActionPerformed(evt);
            }
        });

        tabelPendaftaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelPendaftaran);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(tombolBaru))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboPengajar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioLunas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioBelumLunas)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tombolSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(tombolUbah)
                        .addGap(18, 18, 18)
                        .addComponent(tombolHapus)
                        .addGap(238, 238, 238))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPengajar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioLunas)
                    .addComponent(jRadioBelumLunas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolBaru)
                    .addComponent(tombolSimpan)
                    .addComponent(tombolUbah)
                    .addComponent(tombolHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        App.menuView.pendaftaranView = null;
    }//GEN-LAST:event_formInternalFrameClosed

    private void tombolBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tombolBaruActionPerformed

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        // TODO add your handling code here:
        siswa = App.masterService.getByNameSiswa(comboMapel.getSelectedItem().toString());
        produk.setId(textId.getText());
        produk.setNama(textNama.getText());
        produk.setSatuan(satuan);
        produk.setHargaPokok(Double.parseDouble(textPokok.getText()));
        produk.setHargaJual(Double.parseDouble(textJual.getText()));
        produk.setStok(Integer.parseInt(textStok.getText()));
        
        App.masterService.simpanProduk(produk);
        refreshTable();
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void jRadioBelumLunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBelumLunasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioBelumLunasActionPerformed

    private void jRadioLunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioLunasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioLunasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboMapel;
    private javax.swing.JComboBox<String> comboPengajar;
    private javax.swing.JComboBox<String> comboSiswa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioBelumLunas;
    private javax.swing.JRadioButton jRadioLunas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPendaftaran;
    private javax.swing.JButton tombolBaru;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JButton tombolUbah;
    // End of variables declaration//GEN-END:variables
    
    public class ProdukTableModel extends AbstractTableModel{

        private List<Produk> listProduk = new ArrayList<>();
        private final String HEADER[] = {"ID", "NAMA", "SATUAN", "H. POKOK", "H. JUAL", "STOK"};

        public ProdukTableModel(List<Produk> listProduk) {
            this.listProduk = listProduk;
        }
        
        @Override
        public int getRowCount() {
            return listProduk.size();
        }

        @Override
        public int getColumnCount() {
            return HEADER.length;
        }

        @Override
        public String getColumnName(int i) {
            return HEADER[i];
        }

        @Override
        public Object getValueAt(int i, int i1) {
            Produk p = listProduk.get(i);
            switch(i1){
                case 0:
                    return p.getId();
                case 1:
                    return p.getNama();
                case 2:
                    return p.getSatuan().getNama();
                case 3:
                    return p.getHargaPokok();
                case 4:
                    return p.getHargaJual();
                case 5:
                    return p.getStok();
                default:
                    return null;
            }
        }
        
    }
}
